# Generated by Django 4.1.6 on 2023-02-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoromodel',
            name='pomodoro',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
